example = ("example")
print("This is an example and has no error.")
Name = ("Collin Bowser.")
print("My name is Collin Bowser,and my favourite artist is XXXTENTACION.")
vacation = ("Bahamas")
print ("If I was able to go on vacation, It would be to the Bahamas.")
hobby = ("Music, Rapping.")
print("My hobby I like to do is, Music.")
print("Today's date is, 07/15/20")